#!/bin/sh
#
#
#  Copyright (C) 2011, Joji Antony
#  This file is part of MegaBolt.
#   MegaBolt is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#  MegaBolt is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with MegaBolt.  If not, see <http://www.gnu.org/licenses/>.
#
./clean
qmake -project
echo "QT += network">>MegaBolt.pro
echo "CONFIG += thread">>MegaBolt.pro
qmake MegaBolt.pro
make
