#!/bin/bash
#
#
#  Copyright (C) 2011, Joji Antony
#  This file is part of MegaBolt.
#   MegaBolt is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#  MegaBolt is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with MegaBolt.  If not, see <http://www.gnu.org/licenses/>.
#
rm *~ 2>/dev/null
rm *# 2>/dev/null
for i in `ls -a|grep '~'`
do
    rm $i
done
make clean
rm -f timing_file down_file thread_file 2>/dev/null
rm -f Makefile errfile MegaBolt MegaBolt.pro 2>/dev/null
