######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 3 19:17:37 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mega_http.h mega_httpdownthread.h
SOURCES += mega_http.cpp mega_httpdownthread.cpp test.cpp
QT += network
CONFIG += thread
