######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 24 00:26:55 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += threads.h
SOURCES += threads.cpp
